### ISSUE TITLE
Available on Mac

### ISSUE THREAD

**Issue by the-mauricio** [cl-auto-poster/craigslist-auto-poster#1]
Hello, is this still available on MAC?

**Comment by JustinG2022** [comment]
Were you able to find out, I tried looking everywhere for an installation guide but nothing.

**Comment by cl-auto-poster** [comment]
Hi Justin and Mauricio,

You can find the Craigslist auto poster tutorial video here on our YouTube channel:

https://youtu.be/ucWDKZqGtNg?feature=shared

In regards to the Mac version, we should I have the Mac version released within a week or so...

**Comment by cl-auto-poster** [comment]
Hi Everyone, we have released the Mac version of the Craigslist Relister and it can be downloaded here:

https://github.com/cl-auto-poster/craigslist-auto-poster
