### ISSUE TITLE
Payment 

### ISSUE THREAD

**Issue by Croco24** [cl-auto-poster/craigslist-auto-poster#2]
I did my payment. 
Customer services please

**Comment by cl-auto-poster** [comment]
Hi Croco24,

The payment you made was for the software to use it NOT for Craigslist itself, Craigslist posts are a separate cost charged by Craigslist...

**Comment by Croco24** [comment]
Thats response not help me .
I help to use this software
Help me to use on the right way please

**Comment by Croco24** [comment]
Send me the link to pay on the right way
Customers support
