### ISSUE TITLE
IP Address Configuration & Craigslist Auto-Posting

### ISSUE THREAD

**Issue by mysongbd** [cl-auto-poster/craigslist-auto-poster#3]
I am seeking assistance with two key functionalities:

Setting the IP Address: Could you provide guidance on how to configure or set the IP address within the context of this repository or project? Any relevant documentation or instructions on setting the IP address would be highly appreciated.

Automating Craigslist Postings: I am interested in automating Craigslist postings to specific sections. Could anyone suggest an approach or provide examples of how to automate posts using this repository or any recommended tools? It's essential that the automation adheres to Craigslist's terms of service and avoids manual intervention for recurring posts.

Any help or pointers on these issues would be greatly appreciated!

**Comment by cl-auto-poster** [comment]
Hi Alam,

This software doesn't set any ip addresses for you, that is something you have to configure on your computers network settings. This software only reposts your Craigslist services or gigs for you on auto-pilot based on the frequency setting you set next to the service or gig you want to repost. When you login to your craigslist account in the software there is a drop down menu that appears next to each one of your post that has different frequency settings you can set to have it automatically repost that post for you based on that interval you choose. See the attached screenshot  
![craigslistrelister_action_screenshot](https://github.com/user-attachments/assets/c755e323-eedd-42f6-bb02-add2d1d9ccaf)

Best regards
