### ISSUE TITLE
Options Greyed Out

### ISSUE THREAD

**Issue by dillingerdisco7** [cl-auto-poster/craigslist-auto-poster#4]
Interface brings up the site just fine, pops the extra "RePost" section next to my postings, but the option is greyed out on all of them, just defaulted to "Never". 

Can't click anything. Is there something I am missing?

Win10

![Untitled](https://github.com/user-attachments/assets/ea2d2d71-fb0b-4911-adc6-30aed93b5e94)

**Comment by cl-auto-poster** [comment]
Hi dillingerdisco7, the app doesn't currently support reposting free Craigslist posts, it only supports paid posts for example services, Gigs, paid product listings, but we are currently working on adding free repost support as well it is just not ready yet, we should have it ready in the next upcoming month or so, I will keep you updated here on this thread when it is ready!

Best regards,
Technical Support
CLRePoster.com
